import dotenv from "dotenv";

dotenv.config();

export const env = {
  PORT: process.env.PORT || 5000,
  MONGO_URI: process.env.MONGO_URI,

  JWT_CUSTOMER_SECRET: process.env.JWT_CUSTOMER_SECRET,
  JWT_ADMIN_SECRET: process.env.JWT_ADMIN_SECRET,

  JWT_CUSTOMER_EXPIRES: process.env.JWT_CUSTOMER_EXPIRES || "15m",
  JWT_ADMIN_EXPIRES: process.env.JWT_ADMIN_EXPIRES || "20m",

  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
  TWILIO_VERIFY_SID: process.env.TWILIO_VERIFY_SID,

  BREVO_API_KEY: process.env.BREVO_API_KEY,

  BASE_URL: process.env.BASE_URL,
  FRONTEND_URL: process.env.FRONTEND_URL,

  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,

  SHIPROCKET_EMAIL: process.env.SHIPROCKET_EMAIL,
  SHIPROCKET_PASSWORD: process.env.SHIPROCKET_PASSWORD,
  SHIPROCKET_PICKUP_LOCATION: process.env.SHIPROCKET_PICKUP_LOCATION,

  PAYU_KEY: process.env.PAYU_KEY,
  PAYU_SALT: process.env.PAYU_SALT,
};
